adventuring fellows depend on ai library
compiler error:
/usr/bin/ld: /tmp/ccn4NIx1.ltrans32.ltrans.o: in function `fellowutils::SpawnFellow(CCharEntity*, unsigned int, bool)':
/usr/include/c++/11/bits/unique_ptr.h:962: undefined reference to `CFellowController::CFellowController(CCharEntity*, CFellowEntity*)'